server:
  port:8082
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sonarexample
    username: sonaruser
    password: sonaruser
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always